-- DEMO: seed de demonstração para a reunião do fundo (6 diagnósticos + planos).
-- Colar no SQL Editor do Dashboard EU DEPOIS de aplicar a migration 0003_demo_saas.sql.
-- Gerado por scripts/gen-seed.mjs. owner_id=NULL (públicos). O user demo@ é criado à parte pelo Dashboard.
-- Idempotente: apaga seeds anteriores desta demo pelo prefixo do company_name antes de reinserir.

delete from public.plans p using public.diagnostics d
  where p.diagnostic_id = d.id and d.company_name in ('MetalAçor, Lda.', 'Hotel Caldeira Verde', 'SuperIlha Distribuição, S.A.', 'TransAtlântico Logística, Lda.', 'Lar Solar do Monte', 'LinhaViva Contact Center, S.A.');
delete from public.diagnostics
  where company_name in ('MetalAçor, Lda.', 'Hotel Caldeira Verde', 'SuperIlha Distribuição, S.A.', 'TransAtlântico Logística, Lda.', 'Lar Solar do Monte', 'LinhaViva Contact Center, S.A.');

with d as (
  insert into public.diagnostics
    (created_at, company_name, sector, headcount_band, risks, last_actions, priority, budget_band, contact_email, owner_id)
  values (now() - interval '42 days', 'MetalAçor, Lda.', 'Metalomecânica', '51_200', ARRAY['trabalho em altura', 'químicos']::text[], 'Ação pontual de EPI em 2025', 'reducao_acidentes', '15.000 a 30.000 €', 'geral@metalacor.pt', null)
  returning id
)
insert into public.plans (created_at, diagnostic_id, months, estimated_value, owner_id)
select now() - interval '42 days', id, '{"leitura_geral":"Empresa industrial com exposição a trabalho em altura e agentes químicos. O plano prioriza as obrigações legais de segurança e a proteção coletiva antes de evoluir para cultura preventiva e gestão de equipas.","meses":[{"mes":1,"catalogo_id":"seguranca-saude-trabalho","titulo":"Segurança e saúde no trabalho","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para metalomecânica."},{"mes":2,"catalogo_id":"trabalho-altura","titulo":"Trabalho em altura","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para metalomecânica."},{"mes":3,"catalogo_id":"manuseio-quimicos","titulo":"Manuseio seguro de produtos químicos","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para metalomecânica."},{"mes":4,"catalogo_id":"uso-epi-epc","titulo":"Uso de EPI e EPC — cuidado com as mãos","area":"seguranca","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para metalomecânica."},{"mes":5,"catalogo_id":"primeiros-socorros","titulo":"Primeiros socorros","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para metalomecânica."},{"mes":6,"catalogo_id":"comportamento-seguro","titulo":"Comportamento seguro e preventivo","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: trabalho em altura, químicos."},{"mes":7,"catalogo_id":"ergonomia","titulo":"Ergonomia e movimentação manual de cargas","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para metalomecânica."},{"mes":8,"catalogo_id":"ginastica-laboral","titulo":"Ginástica laboral","area":"especiais","duracao_h":2,"justificativa":"Ação de envolvimento e cultura para toda a organização."},{"mes":9,"catalogo_id":"ler-dort","titulo":"Prevenção de LER/DORT","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: trabalho em altura, químicos."},{"mes":10,"catalogo_id":"qualidade-5s-8s","titulo":"Qualidade total — 5S e 8S","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":11,"catalogo_id":"combate-assedio","titulo":"Combate ao assédio no trabalho","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para metalomecânica."},{"mes":12,"catalogo_id":"gestao-conflitos","titulo":"Gestão de conflitos","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."}]}'::jsonb, 9600, null from d;

with d as (
  insert into public.diagnostics
    (created_at, company_name, sector, headcount_band, risks, last_actions, priority, budget_band, contact_email, owner_id)
  values (now() - interval '35 days', 'Hotel Caldeira Verde', 'Hotelaria', '11_50', ARRAY['atendimento ao público']::text[], 'Formação de acolhimento em 2024', 'clima_motivacao', '5.000 a 15.000 €', 'rh@caldeiraverde.pt', null)
  returning id
)
insert into public.plans (created_at, diagnostic_id, months, estimated_value, owner_id)
select now() - interval '35 days', id, '{"leitura_geral":"Unidade hoteleira açoriana focada na experiência do hóspede. O plano cobre as bases legais de segurança e higiene e investe fortemente em atendimento, clima e bem-estar das equipas.","meses":[{"mes":1,"catalogo_id":"seguranca-saude-trabalho","titulo":"Segurança e saúde no trabalho","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para hotelaria."},{"mes":2,"catalogo_id":"primeiros-socorros","titulo":"Primeiros socorros","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para hotelaria."},{"mes":3,"catalogo_id":"combate-assedio","titulo":"Combate ao assédio no trabalho","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para hotelaria."},{"mes":4,"catalogo_id":"ergonomia","titulo":"Ergonomia e movimentação manual de cargas","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para hotelaria."},{"mes":5,"catalogo_id":"servico-cliente","titulo":"Gestão do serviço ao cliente","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":6,"catalogo_id":"atendimento-cliente","titulo":"Atendimento ao cliente","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":7,"catalogo_id":"qualidade-vida-stress","titulo":"Qualidade de vida e gestão do stress","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de hotelaria."},{"mes":8,"catalogo_id":"ginastica-laboral","titulo":"Ginástica laboral","area":"especiais","duracao_h":2,"justificativa":"Ação de envolvimento e cultura para toda a organização."},{"mes":9,"catalogo_id":"motivacao-palestra-show","titulo":"Motivação (palestra-show)","area":"gestao","duracao_h":2,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":10,"catalogo_id":"comunicacao-relacionamento","titulo":"Comunicação e relacionamento nas equipas","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":11,"catalogo_id":"saude-mental-emocional","titulo":"Saúde mental e emocional","area":"saude","duracao_h":4,"justificativa":"Reforça a saúde e o bem-estar das equipas de hotelaria."},{"mes":12,"catalogo_id":"gestao-conflitos","titulo":"Gestão de conflitos","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."}]}'::jsonb, 8080, null from d;

with d as (
  insert into public.diagnostics
    (created_at, company_name, sector, headcount_band, risks, last_actions, priority, budget_band, contact_email, owner_id)
  values (now() - interval '28 days', 'SuperIlha Distribuição, S.A.', 'Retalho alimentar', 'mais_200', ARRAY['esforço repetitivo', 'turnos noturnos']::text[], null, 'reducao_acidentes', 'mais de 30.000 €', null, null)
  returning id
)
insert into public.plans (created_at, diagnostic_id, months, estimated_value, owner_id)
select now() - interval '28 days', id, '{"leitura_geral":"Retalhista de grande dimensão com trabalho repetitivo e por turnos. O plano combina segurança e ergonomia com ações de saúde para reduzir sinistralidade e absentismo.","meses":[{"mes":1,"catalogo_id":"seguranca-saude-trabalho","titulo":"Segurança e saúde no trabalho","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para retalho alimentar."},{"mes":2,"catalogo_id":"primeiros-socorros","titulo":"Primeiros socorros","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para retalho alimentar."},{"mes":3,"catalogo_id":"ergonomia","titulo":"Ergonomia e movimentação manual de cargas","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para retalho alimentar."},{"mes":4,"catalogo_id":"uso-epi-epc","titulo":"Uso de EPI e EPC — cuidado com as mãos","area":"seguranca","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para retalho alimentar."},{"mes":5,"catalogo_id":"ler-dort","titulo":"Prevenção de LER/DORT","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: esforço repetitivo, turnos noturnos."},{"mes":6,"catalogo_id":"comportamento-seguro","titulo":"Comportamento seguro e preventivo","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: esforço repetitivo, turnos noturnos."},{"mes":7,"catalogo_id":"perturbacoes-sono","titulo":"Perturbações do sono e desempenho","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de retalho alimentar."},{"mes":8,"catalogo_id":"ginastica-laboral","titulo":"Ginástica laboral","area":"especiais","duracao_h":2,"justificativa":"Ação de envolvimento e cultura para toda a organização."},{"mes":9,"catalogo_id":"qualidade-5s-8s","titulo":"Qualidade total — 5S e 8S","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":10,"catalogo_id":"combate-assedio","titulo":"Combate ao assédio no trabalho","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para retalho alimentar."},{"mes":11,"catalogo_id":"servico-cliente","titulo":"Gestão do serviço ao cliente","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":12,"catalogo_id":"qualidade-vida-stress","titulo":"Qualidade de vida e gestão do stress","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de retalho alimentar."}]}'::jsonb, 8080, null from d;

with d as (
  insert into public.diagnostics
    (created_at, company_name, sector, headcount_band, risks, last_actions, priority, budget_band, contact_email, owner_id)
  values (now() - interval '21 days', 'TransAtlântico Logística, Lda.', 'Transportes e logística', '51_200', ARRAY['condução']::text[], 'Reciclagem de condução em 2025', 'reducao_acidentes', '15.000 a 30.000 €', 'pessoas@translantico.pt', null)
  returning id
)
insert into public.plans (created_at, diagnostic_id, months, estimated_value, owner_id)
select now() - interval '21 days', id, '{"leitura_geral":"Operador logístico com frota significativa. O plano concentra-se na segurança rodoviária e no comportamento seguro, complementado com gestão de risco e literacia financeira das equipas.","meses":[{"mes":1,"catalogo_id":"seguranca-saude-trabalho","titulo":"Segurança e saúde no trabalho","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para transportes e logística."},{"mes":2,"catalogo_id":"primeiros-socorros","titulo":"Primeiros socorros","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para transportes e logística."},{"mes":3,"catalogo_id":"direcao-defensiva","titulo":"Direção defensiva","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: condução."},{"mes":4,"catalogo_id":"uso-epi-epc","titulo":"Uso de EPI e EPC — cuidado com as mãos","area":"seguranca","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para transportes e logística."},{"mes":5,"catalogo_id":"conducao-segura-economica","titulo":"Condução segura e económica","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: condução."},{"mes":6,"catalogo_id":"comportamento-seguro","titulo":"Comportamento seguro e preventivo","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: condução."},{"mes":7,"catalogo_id":"ergonomia","titulo":"Ergonomia e movimentação manual de cargas","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para transportes e logística."},{"mes":8,"catalogo_id":"ginastica-laboral","titulo":"Ginástica laboral","area":"especiais","duracao_h":2,"justificativa":"Ação de envolvimento e cultura para toda a organização."},{"mes":9,"catalogo_id":"perturbacoes-sono","titulo":"Perturbações do sono e desempenho","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de transportes e logística."},{"mes":10,"catalogo_id":"combate-assedio","titulo":"Combate ao assédio no trabalho","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para transportes e logística."},{"mes":11,"catalogo_id":"gestao-risco","titulo":"Gestão do risco","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":12,"catalogo_id":"planeamento-economico","titulo":"Planeamento económico pessoal","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."}]}'::jsonb, 8400, null from d;

with d as (
  insert into public.diagnostics
    (created_at, company_name, sector, headcount_band, risks, last_actions, priority, budget_band, contact_email, owner_id)
  values (now() - interval '14 days', 'Lar Solar do Monte', 'Cuidados a idosos', '11_50', ARRAY['esforço repetitivo']::text[], 'Sem formação estruturada', 'obrigacoes_legais', '5.000 a 15.000 €', null, null)
  returning id
)
insert into public.plans (created_at, diagnostic_id, months, estimated_value, owner_id)
select now() - interval '14 days', id, '{"leitura_geral":"Estrutura residencial para idosos com forte carga física no cuidado. O plano garante as obrigações legais e reforça ergonomia, saúde mental e comunicação das equipas cuidadoras.","meses":[{"mes":1,"catalogo_id":"seguranca-saude-trabalho","titulo":"Segurança e saúde no trabalho","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para cuidados a idosos."},{"mes":2,"catalogo_id":"primeiros-socorros","titulo":"Primeiros socorros","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para cuidados a idosos."},{"mes":3,"catalogo_id":"ergonomia","titulo":"Ergonomia e movimentação manual de cargas","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para cuidados a idosos."},{"mes":4,"catalogo_id":"combate-assedio","titulo":"Combate ao assédio no trabalho","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para cuidados a idosos."},{"mes":5,"catalogo_id":"ler-dort","titulo":"Prevenção de LER/DORT","area":"seguranca","duracao_h":4,"justificativa":"Responde aos riscos declarados: esforço repetitivo."},{"mes":6,"catalogo_id":"uso-epi-epc","titulo":"Uso de EPI e EPC — cuidado com as mãos","area":"seguranca","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para cuidados a idosos."},{"mes":7,"catalogo_id":"saude-mental-emocional","titulo":"Saúde mental e emocional","area":"saude","duracao_h":4,"justificativa":"Reforça a saúde e o bem-estar das equipas de cuidados a idosos."},{"mes":8,"catalogo_id":"ginastica-laboral","titulo":"Ginástica laboral","area":"especiais","duracao_h":2,"justificativa":"Ação de envolvimento e cultura para toda a organização."},{"mes":9,"catalogo_id":"higiene-saude-oral","titulo":"Higiene e saúde oral","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de cuidados a idosos."},{"mes":10,"catalogo_id":"qualidade-vida-stress","titulo":"Qualidade de vida e gestão do stress","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de cuidados a idosos."},{"mes":11,"catalogo_id":"comunicacao-relacionamento","titulo":"Comunicação e relacionamento nas equipas","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":12,"catalogo_id":"gestao-conflitos","titulo":"Gestão de conflitos","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."}]}'::jsonb, 8080, null from d;

with d as (
  insert into public.diagnostics
    (created_at, company_name, sector, headcount_band, risks, last_actions, priority, budget_band, contact_email, owner_id)
  values (now() - interval '7 days', 'LinhaViva Contact Center, S.A.', 'Contact center', 'mais_200', ARRAY['atendimento ao público']::text[], 'Workshop de stress em 2024', 'clima_motivacao', '15.000 a 30.000 €', null, null)
  returning id
)
insert into public.plans (created_at, diagnostic_id, months, estimated_value, owner_id)
select now() - interval '7 days', id, '{"leitura_geral":"Operação de contact center com elevada carga emocional e prioridade na saúde mental. O plano equilibra as bases de segurança com um forte eixo de bem-estar psicológico e gestão de conflitos.","meses":[{"mes":1,"catalogo_id":"seguranca-saude-trabalho","titulo":"Segurança e saúde no trabalho","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para contact center."},{"mes":2,"catalogo_id":"primeiros-socorros","titulo":"Primeiros socorros","area":"seguranca","duracao_h":8,"justificativa":"Formação com obrigação legal, prioritária para contact center."},{"mes":3,"catalogo_id":"combate-assedio","titulo":"Combate ao assédio no trabalho","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para contact center."},{"mes":4,"catalogo_id":"ergonomia","titulo":"Ergonomia e movimentação manual de cargas","area":"saude","duracao_h":4,"justificativa":"Formação com obrigação legal, prioritária para contact center."},{"mes":5,"catalogo_id":"saude-mental-emocional","titulo":"Saúde mental e emocional","area":"saude","duracao_h":4,"justificativa":"Reforça a saúde e o bem-estar das equipas de contact center."},{"mes":6,"catalogo_id":"qualidade-vida-stress","titulo":"Qualidade de vida e gestão do stress","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de contact center."},{"mes":7,"catalogo_id":"gestao-conflitos","titulo":"Gestão de conflitos","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":8,"catalogo_id":"ginastica-laboral","titulo":"Ginástica laboral","area":"especiais","duracao_h":2,"justificativa":"Ação de envolvimento e cultura para toda a organização."},{"mes":9,"catalogo_id":"perturbacoes-sono","titulo":"Perturbações do sono e desempenho","area":"saude","duracao_h":2,"justificativa":"Reforça a saúde e o bem-estar das equipas de contact center."},{"mes":10,"catalogo_id":"comunicacao-relacionamento","titulo":"Comunicação e relacionamento nas equipas","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":11,"catalogo_id":"servico-cliente","titulo":"Gestão do serviço ao cliente","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."},{"mes":12,"catalogo_id":"inteligencia-emocional","titulo":"Inteligência emocional","area":"gestao","duracao_h":4,"justificativa":"Desenvolve competências de gestão alinhadas com a prioridade declarada."}]}'::jsonb, 8080, null from d;
